### ISSUE TITLE
Idea: Linting support for docker-compose.yml files

### ISSUE THREAD

**Issue by lostintangent** [microsoft/compose-language-service#84]
It would make it a lot simpler to author `Dockerfile` and `docker-compose.yml` files if you could view actionable linting errors from within VS Code. For example, Docker Compose includes JSON schema files for its various formats (e.g. [v2.0](https://github.com/docker/compose/blob/master/compose/config/config_schema_v2.0.json)) that document how to determine whether a compose file is valid or not.

**Comment by bwateratmsft** [comment]
I've investigated this and ultimately the conclusion I've reached is that without just straight-up copying the functionality of the YAML extension, I could not do as good of a job as they've already done. So rather than try to implement this, I'm going to close this issue, since with #122 it is now much more user-friendly to have both the YAML and Docker extensions' language services for compose working side-by-side.

**Comment by AshutoshSajan** [comment]
> Anyone on this ticket that needs this should be able to get something decent with [Red Hat's YAML extension](https://github.com/redhat-developer/vscode-yaml). You can use something like the following in your `settings.json` file.
> 
> {
>     "yaml.schemas": {
>         "https://raw.githubusercontent.com/docker/cli/master/cli/compose/schema/data/config_schema_v3.8.json": "docker-compose.yml"
>     }
> }

there is no such file on GitHub so which file we should use now? or does any other extension support it?

**Comment by bwateratmsft** [comment]
I'm still able to access that file, what error do you see?

**Comment by AshutoshSajan** [comment]
I am getting an error that could not load the file
